### ISSUE TITLE
Adding the modified yara-python to pip

### ISSUE THREAD

**Issue by ajinabraham** [rednaga/yara-python#4]
```
The yara-python clone and compile steps here are temporarily necessary because we must point directly to our modified version of a Yara branch which includes our DEX Yara module. This step is nessecary until (if?) the original maintainers of Yara merge our module into the master branch.
```

How about adding it to pip as a separate module?

**Comment by strazzere** [comment]
This is definitely an option - however, I do not think it is the correct way to handle this. I believe getting this merged into the actual master branch is the correct way to solve this.

Otherwise, we need to create and maintain our own pip module - where compiling it from source is just as acceptable.
